version: '2'

services:
    db:
        image: mongo:latest
        restart: always
        user: mongodb
        ports:
            - "27017:27017"
        volumes:
            - ./datadir:/data/db
    webapp_oaipmh:
        build:
            context: .
            dockerfile: ./Dockerfile
        user: nobody
        restart: always
        depends_on:
            - db
        ports:
            - "6543:6543"
